application: turbo-writer-tim
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /assets
  static_dir: assets

- url: /img
  static_dir: img

- url: /font
  static_dir: font

- url: /my_account/assets
  static_dir: assets

- url: /template_admin/assets
  static_dir: assets

- url: /project_admin/assets
  static_dir: assets

- url: /template/assets
  static_dir: assets

- url: /project/assets
  static_dir: assets

- url: /template/assignment/assets
  static_dir: assets

- url: /template/variable/assets
  static_dir: assets

- url: /template/document/assets
  static_dir: assets

- url: /template/style/assets
  static_dir: assets

- url: /template/css
  static_dir: css

- url: /template/font/
  static_dir: font

- url: /gallery/
  static_dir: gallery

- url: /images/
  static_dir: images

- url: /how_we_work.html
  static_files: /ui/tempest/how_we_work.html
  upload: /ui/tempest/

- url: /privacy_policy.html
  static_files: /ui/tempest/privacy_policy.html
  upload: /ui/tempest/

- url: /.*
  script: turbowriter.app

libraries:
- name: jinja2
  version: latest
