application: turbo-writer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /ui/basic/stylesheets
  static_dir: ui/basic/stylesheets

- url: /ui/turbo/stylesheets
  static_dir: ui/turbo/stylesheets

- url: /.*
  script: turbowriter.app

libraries:
- name: jinja2
  version: latest
